services:
  redis:
    image: redis:latest
    container_name: whatsapp-redis
    env_file: .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--port", "${REDIS_PORT}"]
    volumes:
      - redis_gurindam:/data
    mem_limit: 20m

  bot:
    build: .
    container_name: whatsapp-lian
    env_file: .env
    ports:
      - "${BAILEYS_PORT}:${BAILEYS_PORT}"  # Menyambungkan port 3040 dari container ke host
    volumes:
      - .:/app  # Menggunakan volume agar perubahan file langsung ter-update di container
    environment:
      - NODE_ENV=production  # Menentukan environment variabel untuk Node.js
    restart: always  # Menjamin container akan restart otomatis jika container berhenti
    mem_limit: 100m
    command: ["node", "bot.js"]
    depends_on:
      - redis

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: whatsapp-cloudflared-tunnel
    env_file: .env
    restart: unless-stopped
    command: tunnel --no-autoupdate --url http://bot:3099
    depends_on:
      - bot

volumes:
  redis_gurindam:
    driver: local
